name: create_flutter_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables: 
  create_flutter_cli: create_flutter_cli

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  io: ^1.0.4
  interact: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
